### ISSUE TITLE
Is this a mini version Epoxy for iOS?

### ISSUE THREAD

**Issue by alouanemed** [airbnb/AloeStackView#14]
Hello, coming from Android using Epoxy for our views, can AloStackView be considered a small variation of what Epoxy can do ? I read in the docs that this stack view is not suitable for longer screen. So are we going to see another library for iOS that achieve the same as Epoxy in Android? Thanks.

**Comment by lauraskelton** [comment]
Epoxy for iOS is a separate framework- we're in the process of open sourcing it as well, and you can expect it before the end of the year!

**Comment by marlimox** [comment]
Hi @alouanemed, thanks for your interest in AloeStackView!

As you mentioned, AloeStackView is not suitable for use on longer screens. Hence, it’s not comparable to what something like Epoxy on Android provides.

You can think of AloeStackView as filling the space between UITableView, which works well for longer screens, and manually laying out your views in a UIStackView or similar for shorter screens.

AloeStackView is more comparable to manually laying out your views, but it’s much simpler and takes a lot less code.

I hope that answers your question! Let me know if I can help you with anything else.

**Comment by alouanemed** [comment]
Thank you!
