### ISSUE TITLE
Insert row animation is different to remove row animation

### ISSUE THREAD

**Issue by harryblam** [airbnb/AloeStackView#24]
Currently when adding a row to the StackView using `insertRow(_ row: UIView, after afterRow: UIView, animated: Bool)`, the stackview increases the space for the next row without animation, and then animates the alpha of the new row.

Is there a reason why it's not using the same method as the `removeRow(_ row: UIView, animated: Bool)` function? This is utilising the standard ios stackview animations by simply animating the `isHidden` property of the `UIStackView`, providing us with a much smoother animation.

If there is no specific reason why the insert animation doesn't mirror this, I can put up a PR with the changes.

Thanks!

**Comment by marlimox** [comment]
Hi @harryblam, thanks for your interest in AloeStackView!

I actually don’t remember the reason for this difference. I believe @fancox was the original author of the row animation code, so she might have some insight to share.

If you’d like to try changing the insert animation in the way you describe and upload a side-by-side comparison of before and after the change, please feel free. That’d probably help make the decision easy.

**Comment by harryblam** [comment]
Hey @marlimox cheers for the quick reply.

Upon further analysis I can see that there is a method for `setRowHidden` which is exactly what i'm looking for, so no need for changes as stated above. 

I was trying to add elements to my UI reactively using insert, but I can now see that this library plays better if you add all rows to the UI first (some in a hidden state), then go ahead and unhide them reactively.

Thanks for the awesome library, seems very useful 👍🏻
