### ISSUE TITLE
Sticky Headers

### ISSUE THREAD

**Issue by cohen72** [airbnb/AloeStackView#35]
Is there a way to create an effect similar to stick section headers in `UITableView`?

**Comment by FlorianLdt** [comment]
Hmm if you mean by that that the header will stick on the top when you scroll, I doubt there is a way for that and I think this would be out of scope for `AloeStackView` in order to remains "A simple class for laying out a collection of views".

**Comment by apang42** [comment]
Thank you for your suggestion! We're tracking this issue here: https://github.com/airbnb/AloeStackView/issues/43
