### ISSUE TITLE
Stackview size

### ISSUE THREAD

**Issue by ladislas** [airbnb/AloeStackView#41]
Hi there! --

Following my previous question about auto-layout, I'm wondering how it could be possible to get the actual size of the AloeStackview once all the rows and separators have been laid out.

I'm using them a lot in modal pop-ups and cells to display information. My goal is to have the modal or cell resize to the aloestackview size if I add or remove a row.

Thanks a lot!
Ladislas

**Comment by florianldt** [comment]
Since it's a UIScrollView, what about the `contentSize` property?

**Comment by florianldt** [comment]
My previous answer was maybe a little bit confusing, so I built a fast example to illustrate and might be useful for people having the same issue in the future. If I understand well what you want, you may have a start of an answer in this [Gist](https://gist.github.com/florianldt/69d4e53d6ebf1507a15b26dba77894b9).

Demo:
![issue41](https://user-images.githubusercontent.com/9365651/53537288-cdee2380-3b4c-11e9-93cd-a67d30a53bc4.gif)

Feel free to reach me for question or if I miss something.

**Comment by ladislas** [comment]
It looks about right! Thanks a lot Florian for your quick help! :)

I'll try it today and let you know!

**Comment by florianldt** [comment]
You are welcome. If you were able to solve your issue, feel free to close the thread.

**Comment by ladislas** [comment]
I've juste tested and it works as I excepted, thank you so much! :)

Actually, I had found a solution which was doing the same but as I'm using round corners at the same time, I've pinpoint a different issue that was preventing the view from being visible.

I'll try and find a another solution.
