### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by IceFloe** [airbnb/AloeStackView#45]
There is some warnings in library, are you planning to fix them?

**Comment by florianldt** [comment]
By what I saw, here are the few changes needed to quiet the warning on Swift 5.

<img width="269" alt="Screen Shot 2019-04-01 at 4 27 47 PM" src="https://user-images.githubusercontent.com/9365651/55310498-859f8980-549b-11e9-91da-03ee4d1384dd.png">

PR is on the way.

**Comment by IceFloe** [comment]
Yes, thanks!

**Comment by florianldt** [comment]
PR [#46](https://github.com/airbnb/AloeStackView/pull/46) for swift 5 support has been merged. 

Feel free to close the issue if it’s ok for you.

**Comment by IceFloe** [comment]
Thx! Will wait for a new version then.
