### ISSUE TITLE
Improved touch and tap handling of cells

### ISSUE THREAD

**Issue by colinhumber** [airbnb/AloeStackView#54]
There are a couple of issues that would be great to see improved:
- while a content view is highlighted, moving your finger in and out of the cell should adjust the highlight state accordingly. This would be consistent with how highlight states work with UITableViews
- UIControls within a content view do not receive touches when the tap gesture on the cell is enabled

**Comment by apang42** [comment]
Resolved here: https://github.com/airbnb/AloeStackView/pull/55
