### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by tereks** [airbnb/AloeStackView#56]
Hi, can we have swift 5 support?

**Comment by yanamura** [comment]
@tereks swift5 support was already merged
https://github.com/airbnb/AloeStackView/pull/46

**Comment by tereks** [comment]
I mean mention swift 5 in podspec file
<img width="717" alt="Снимок экрана 2019-06-04 в 8 15 29" src="https://user-images.githubusercontent.com/1751247/58844445-70b0c380-86a1-11e9-8ae2-f214baf3a8d8.png">

**Comment by apang42** [comment]
Hi @tereks, the podspec is updated in the latest release: https://github.com/airbnb/AloeStackView/releases/tag/v1.1.0
