### ISSUE TITLE
Cannot build with `swift build`

### ISSUE THREAD

**Issue by endore8** [airbnb/AloeStackView#83]
When `AloeStackView` is used as a dependency in a Swift Package, the build fails with:
`AloeStackView/AloeStackView.swift:16:8: error: no such module 'UIKit'`

It's because Swift Package is universal and so, `UIKit` might not be available. 
The fix is adding code in `#if canImport(UIKit) ... #endif` block.

**Comment by Kayst83** [comment]
![Image](https://github.com/user-attachments/assets/0f94ed1f-9e31-4db7-8256-f4d7168cf0e0)
